/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspraktikum10;
/**
 *
 * @author Risvandiani
 */
import java.io.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
public class FormDosen extends javax.swing.JFrame {
    Statement stmt;
    Connection con;
    String url = "jdbc:mysql://localhost:3306/coba";
    /**
     * Creates new form FormDosen
     */
    public FormDosen() {
        initComponents();
    }
    public void kosong(){
        NIDNTF.setText("");
        NamaDosenTF.setText("");
        AlamatTF.setText("");
        GajiPokokTF.setText("");
        TunjanganTF.setText("");
        TotalGajiTF.setText("");
        NIDNTF.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NIDNTF = new javax.swing.JTextField();
        NamaDosenTF = new javax.swing.JTextField();
        AlamatTF = new javax.swing.JTextField();
        GajiPokokTF = new javax.swing.JTextField();
        TunjanganTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TotalGajiTF = new javax.swing.JTextField();
        HitungTF = new javax.swing.JToggleButton();
        SimpanTF = new javax.swing.JToggleButton();
        KeluarTF = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("NIDN");

        jLabel2.setText("Nama Dosen");

        jLabel3.setText("Alamat");

        jLabel4.setText("Gaji Pokok");

        jLabel5.setText("Tunjangan");

        GajiPokokTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajiPokokTFActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Gaji");

        TotalGajiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalGajiTFActionPerformed(evt);
            }
        });

        HitungTF.setText("Hitung");
        HitungTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungTFActionPerformed(evt);
            }
        });

        SimpanTF.setText("Simpan");
        SimpanTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SimpanTFMouseClicked(evt);
            }
        });

        KeluarTF.setText("Keluar");
        KeluarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIDNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaDosenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GajiPokokTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TunjanganTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalGajiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(HitungTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SimpanTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KeluarTF)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(NIDNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(NamaDosenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(AlamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GajiPokokTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TunjanganTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TotalGajiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HitungTF)
                    .addComponent(SimpanTF)
                    .addComponent(KeluarTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GajiPokokTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajiPokokTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GajiPokokTFActionPerformed

    private void SimpanTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SimpanTFMouseClicked
        // TODO add your handling code here:
        String NIDN = NIDNTF.getText();
        String NamaDosen = NamaDosenTF.getText();
        String Alamat = AlamatTF.getText();
        String GajiPokok = GajiPokokTF.getText();
        String Tunjangan = TunjanganTF.getText();
        String TotalGaji = TotalGajiTF.getText();
        JOptionPane.showMessageDialog(null, NIDN+", "+NamaDosen+" ,"+Alamat+" ,"+GajiPokok+" ,"+Tunjangan+" ,"+TotalGaji);
        try{
            con=DriverManager.getConnection(url,"root","");
            System.out.println("Database ditemukan");
            stmt = con.createStatement();
            String sql="insert into dosen values('"+NIDN+"','"+NamaDosen+"','"+Alamat+"','"+GajiPokok+"','"+Tunjangan+"','"+TotalGaji+"')";
            stmt.executeUpdate(sql);
            kosong();
        }catch(SQLException ex){
            System.err.println("SQLException:"+ex.getMessage());
        }
    }//GEN-LAST:event_SimpanTFMouseClicked

    private void KeluarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarTFActionPerformed
        // TODO add your handling code here:
         int reply = JOptionPane.showConfirmDialog
                    (null, "Yakin ingin keluar?", 
                    "Konfirmasi Keluar Aplikasi",
                    JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
        System.exit(0);
        }else{
        NIDNTF.requestFocus();
        }
    }//GEN-LAST:event_KeluarTFActionPerformed

    private void HitungTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungTFActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(GajiPokokTF.getText());
        int y = Integer.parseInt(TunjanganTF.getText());
        int total = x + y;
        TotalGajiTF.setText(String.valueOf(total));
    }//GEN-LAST:event_HitungTFActionPerformed

    private void TotalGajiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalGajiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalGajiTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Driver ditemukan");
        }catch(Exception e){
            System.out.println("Error"+e);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDosen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatTF;
    private javax.swing.JTextField GajiPokokTF;
    private javax.swing.JToggleButton HitungTF;
    private javax.swing.JToggleButton KeluarTF;
    private javax.swing.JTextField NIDNTF;
    private javax.swing.JTextField NamaDosenTF;
    private javax.swing.JToggleButton SimpanTF;
    private javax.swing.JTextField TotalGajiTF;
    private javax.swing.JTextField TunjanganTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
